wandb_version: 1

criterion:
  desc: null
  value: gini
max_depth:
  desc: null
  value: 3
min_samples_split:
  desc: null
  value: 5
test_size:
  desc: null
  value: 0.21909843639255333
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698674991.877208
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.12
      5: 0.15.12
      8:
      - 4
      - 5
      13: darwin-arm64
