wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698667336.645925
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 19
      - 23
      4: 3.10.12
      5: 0.15.12
      8:
      - 4
      - 5
      13: darwin-arm64
test_size:
  desc: null
  value: 0.5
max_depth:
  desc: null
  value: 1
min_samples_split:
  desc: null
  value: 3
criterion:
  desc: null
  value: gini
